# Alacritty Configuration File - Gruvbox x Lilex Edition (Ballu-Mode)

[window]
opacity = 0.95
blur = true

[scrolling]
history = 10000

[font]
size = 12.0

[font.normal]
family = "Lilex Nerd Font"
style = "Regular"

[font.bold]
family = "Lilex Nerd Font"
style = "Bold"

[font.italic]
family = "Lilex Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Lilex Nerd Font"
style = "Bold Italic"

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500

# Gruvbox Colors (Dark)
[colors.primary]
background = "#0d1117"
foreground = "#d0e7ff"

[colors.normal]
black   = "#1c1f26"
red     = "#5e81ac"
green   = "#81a1c1"
yellow  = "#88c0d0"
blue    = "#5e81ac"
magenta = "#81a1c1"
cyan    = "#8fbcbb"
white   = "#d8dee9"

[colors.bright]
black   = "#4c566a"
red     = "#81a1c1"
green   = "#8fbcbb"
yellow  = "#b4dce5"
blue    = "#5fa8d3"
magenta = "#a3bfe3"
cyan    = "#a0cbe2"
white   = "#e6efff"
