# Alacritty Configuration File - Gruvbox x Lilex Edition (Ballu-Mode)

[window]
opacity = 0.95
blur = true

[scrolling]
history = 10000

[font]
size = 12.0

[font.normal]
family = "Lilex Nerd Font"
style = "Regular"

[font.bold]
family = "Lilex Nerd Font"
style = "Bold"

[font.italic]
family = "Lilex Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Lilex Nerd Font"
style = "Bold Italic"

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500

# Gruvbox Colors (Dark)
[colors.primary]
background = "#1d2021"   # main background
foreground = "#ebdbb2"   # main text

[colors.normal]
black   = "#282828"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"

[colors.bright]
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#ebdbb2"

